from enum import Enum


class Permission(str, Enum):
    CREATE_USER = "CREATE_USER"
    MANAGE_TEAMS = "MANAGE_TEAMS"
    MANAGE_PLAYERS = "MANAGE_PLAYERS"
    MANAGE_MATCHES = "MANAGE_MATCHES"
    RUN_QUERIES = "RUN_QUERIES"
    GENERATE_REPORTS = "GENERATE_REPORTS"
    VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS"
